global:
    #The smarthost and SMTP sender used for mail notifications.
    smtp_smarthost: 'smtp.live.com:587' #gmail: smtp.gmail.com:587
    smtp_from: 'luumarodrigues@hotmail.com' #seu email
    smtp_auth_identity: 'luumarodrigues@hotmail.com' #seu email
    #smtp_auth_username: ''
    #smtp_auth_password: ''
    smtp_require_tls: true
templates:
- "/etc/alertmanager/template/*.tmpl"
  
route:
    repeat_interval: 30m
    receiver: alert-email

receivers:
- name: alert-email
  email_configs:
  - to: "luumarodrigues@hotmail.com" #destinatário
    auth_username: 'luumarodrigues@hotmail.com' #seu email
    auth_password: 'xxxxxx' #senha_do_app_gerada_pelo_email
    send_resolved: true

## ALERTA SLACK
#route:
#    receiver: 'slack'

#receivers:
#    - name: 'slack'
#        slack_configs:
#            - send_resolved: true
#            username: 'USUÁRIO'
#            channel: '#CANALSLACK'
#            api_url: 'INCOMMING WEBHOOK'