version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/:/etc/prometheus/:ro"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on: 
      - cadvisor
      - node_exporter
      - alertmanager
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/var/lib/docker/:/var/lib/docker:ro"
    depends_on: 
      - redis
    networks:
      - monitoring

  redis:
    image: redis:latest
    container_name: redis
    ports: 
      - "6379:6379"
    networks: 
      - monitoring

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    pid: "host"
    volumes: 
      - "/:/host:ro"
    ports: 
      - "9100:9100"
    cap_add: 
      - SYS_TIME
    networks: 
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager:/etc/alertmanager/:ro"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - monitoring

networks:
    monitoring:
        driver: bridge
      
  