#prometheus global config
#scrape_timeout is set to the global default (10s).
global:
  scrape_interval:     15s #a cada 15s o prometheus irá consultar (scrape) os alvos (targert). É possivel sobrescreve-lo no scrape_configs
  evaluation_interval: 15s #frequencia q o prometheus irá avaliar as regras do rules_files -> criar novos time series -> gerar alertas
  
#rules_files: #local onde é configurado o path do arquivo de qualquer regra que o Prometheus tenha que carregar
  #- "first.rules"
  #- "second.rules"
  
scrape_configs: #onde setamos quais recursos o prometheus irá monitorar
#esse job está consultando a URL: http://localhost:9090/metrics
  - job_name: prometheus #irá coletar as metricas dele mesmo
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: 
        - localhost:9090
#O cadvisor irá coletar as metricas do docker para que o prometheus consiga consumir
  - job_name: cadvisor
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: 
        - cadvisor:8080
  